<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="PostNL" Id="{93e07b44-ce98-4bf0-8ee4-9a497784c1d4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PostNL
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PostNL">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>